version: '3.8'

services:
  mjpg-streamer:
# Build Configuration
    # build:
    #   context: .
    #   dockerfile: Dockerfile
      
# Runtime Configuration
    image: mjpg-streamer
    
    ports:
      - "8080:8080"
    volumes:
      - ./app/src:/app/src
    environment:
      - CAMERA_DEVICE=/dev/video0
      - STREAM_PORT=8080
    restart: always

networks:
  default:
    driver: bridge